# Generated by Django 5.2.3 on 2025-06-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Заголовок', max_length=254, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, help_text='Содержимое',
                                                 null=True, verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/photo')),
                ('publication_attribute', models.BooleanField(default=False, help_text='Признак публикации',
                                                              verbose_name='Признак публикации')),
                ('views', models.PositiveIntegerField(default=0, help_text='Количество просмотров',
                                                      max_length=254, verbose_name='Количество просмотров')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['name'],
            },
        ),
    ]
