# Generated by Django 5.2.3 on 2025-06-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_attribute',
            field=models.BooleanField(help_text='Признак публикации', verbose_name='Признак публикации'),
        ),
    ]
