# Generated by Django 5.2.3 on 2025-06-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_publication_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/photo',
                                    verbose_name='Иллюстрация статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_attribute',
            field=models.BooleanField(verbose_name='Признак публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, max_length=254, verbose_name='Количество просмотров'),
        ),
    ]
