# Generated by Django 5.2.1 on 2025-05-31 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ImageField(help_text='id категории', max_length=20, unique=True, upload_to='',
                                                  verbose_name='id категории')),
                ('name', models.CharField(max_length=254, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.ImageField(help_text='id продукта', max_length=20, unique=True, upload_to='',
                                                 verbose_name='id продукта')),
                ('name', models.CharField(help_text='Наименование', max_length=254, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='описание', null=True,
                                                 verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/photo')),
                ('purchase_price', models.FloatField(default=0, help_text='цена за покупку',
                                                     verbose_name='цена за покупку')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(help_text='категория', on_delete=django.db.models.deletion.CASCADE,
                                               to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['name'],
            },
        ),
    ]
