# Generated by Django 5.2.3 on 2025-06-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_product',
        ),
    ]
