# Generated by Django 5.2.4 on 2025-07-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_category_id_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_unpublish_product', 'Can unpublish product'),
                                                           ('can_delete_products', 'Can delete products')],
                     'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='publication_status',
            field=models.BooleanField(blank=True, default=False, help_text='Признак публикации',
                                      null=True, verbose_name='Признак публикации'),
        ),
    ]
